name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

      - name: Configure Hazel Viewer
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Hazel Viewer
        run: cmake --build build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            bin/hview

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: pip install jinja2

      - name: Configure Hazel
        run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Hazel Viewer
        run: cmake --build build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            bin/hview.exe

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Copy Binaries to Root Folder
        run: cp artifact/hview artifact/hview.exe ${{github.workspace}}

      - name: Release Linux HView
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{github.ref}}
          file: hview

      - name: Release Windows Version of HView
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{github.ref}}
          file: hview.exe
